### ISSUE TITLE
pcap2dev.py does not support encrypted .pcap traffic

### ISSUE THREAD

**Issue by simonsavvi** [etingof/snmpsim#12]
In order to simulate a large switch, we have captured a `pcap` file of an `snmpbulkwalk` of (almost) an entire switch. However, this was done using `SNMPv3` with `-l authPriv`, so the resulting `pcap` file contains encrypted SNMP traffic.

It appears that `pcap2dev.py` has no means to decrypt such a `pcap` file. Is this possible?

(and no, it was not possible to use `snmprec.py` to bulk-walk the switch; the host from which we walked the switch does not have `snmpsim` installed, and we cannot install it there for reasons).

**Comment by etingof** [comment]
It seems technically possible to add SNMPv3 message parsing and deciphering support to the pcap2dev tool. 

What we probably need is to automatically pre-configure SNMPv3 engine to trust SNMP engine ID and the timeliness counters from the snooped packets rather than trying to negotiate them with the peer SNMPv3 engine (which obviously can't happen).

When do you need the SNMPv3 support to become available? Are you considering working on it (and hopefully contribute back to the upstream) or you'd rather want me to tackle this change?

**Comment by simonsavvi** [comment]
As with all things, we needed to convert these `pcap`s to `.snmprec` files yesterday...

I have not considered modifying `pcap2dev.py` or its supporting libraries to support SNMPv3 encrypted traffic, nor will I do so. My Python abilities are so poor I'm more likely to set fire to it than achieve anything useful.

I have translated the `pcap`s into `.snmprec` files using a combination of `tshark` outputting in JSON format and Perl code to translate that, so we no longer have a need for `pcap2dev.py` to support this use case.
