### ISSUE TITLE
can't using my mib file

### ISSUE THREAD

**Issue by EngKhaled91** [etingof/snmpsim#45]
Hello everybody:
I'm trying to simulate snmp agent so I've used snmpsim but I can't use my own mib file 
here is my mib file 
could any one help me on that
thanks for supporting 
[my mib.txt](https://github.com/etingof/snmpsim/files/2331002/my.mib.txt)

**Comment by etingof** [comment]
Have you tried to use the [mib2dev](http://snmplabs.com/snmpsim/building-simulation-data.html#mib-based-synthesis) tool for building simulation data from your MIB? That should work I think.

**Comment by EngKhaled91** [comment]
when I ran mib2dev I get the following results but I'm stell net able to get values using snmpget for example 
![res1](https://user-images.githubusercontent.com/29969831/44772633-0ea5b980-ab77-11e8-8e5f-255647635499.png)
![res2](https://user-images.githubusercontent.com/29969831/44772796-870c7a80-ab77-11e8-8b7a-95cd9a52c858.png)

**Comment by etingof** [comment]
You should save this text into a .snmprec file so that `snmpsimd` could load it. Make sure that SNMP community name you use (snmpwalk -v2c -c <community-name> ...) is the same path to your new `.snmprec` file. The instructions [are here](http://snmplabs.com/snmpsim/simulating-agents.html#simulation-data).

**Comment by EngKhaled91** [comment]
thanks alot for helping it works for me
